### ISSUE TITLE
Not working with Pro Micro

### ISSUE THREAD

**Issue by LaurieY** [jwellman80/ArduinoLightbox#4]
I can't get SGP to connect using a Pro Micro. Sending the commands via realterm it responds OK.
The sketch works with SGP using a nano or a Mega.
Any idea where the problem might lie?

**Comment by jwellman80** [comment]
Yes, the Leonardo and Micro use a 32u4 chip which handles the serial connection differently (very poorly). As such you’ll need to stick with a 328 based variant like the Uno.
